services:
  - type: web
    name: dose-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: ENABLE_SMS_NOTIFICATIONS
        value: "true"
      - key: UPLOAD_DIR
        value: public/uploads
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: BCRYPT_SALT_ROUNDS
        value: "10"
      - key: CORS_ORIGIN
        value: https://dosebsit.netlify.app
      - key: ENABLE_EMAIL_NOTIFICATIONS
        value: "true"
      - key: FRONTEND_URL
        value: https://dosebsit.netlify.app
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: PAYMONGO_PUBLIC_KEY
        value: pk_test_xoFM6owPGQNLYhKuXiWSaDgV
      - key: PAYMONGO_SECRET_KEY
        sync: false 