services:
  # Backend API service
  - type: web
    name: pharmacy-api
    env: node
    region: ohio
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node dist/api/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

  # Frontend service
  - type: web
    name: pharmacy-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://pharmacy-api.onrender.com # Update this with your actual API URL
      - key: VITE_NODE_ENV
        value: production

databases:
  - name: pharmacy-db
    plan: starter
    ipAllowList: [] # only allow internal connections 